version: '3'

services:
  cart-app-dev:
    container_name: 'cart-app'
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '.:/work'
    ports:
      - '3002:3000'
      - '9002:9000'
    links:
      - cart-mysql-dev
    networks:
      - local
    command: 'bash -c "go build -o bin ; ./bin"'
  cart-mysql-dev:
    container_name: 'cart-db'
    image: 'mysql'
    ports:
      - '3308:3306'
    environment:
      MYSQL_CHARSET: utf8
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
      TZ: 'Asia/Tokyo'
    volumes:
      - './mysql/init:/docker-entrypoint-initdb.d'
      - 'mysql:/var/lib/mysql'
    networks:
      - local

volumes:
  mysql:
    driver: 'local'

networks:
  local:
    external: true
