version: '3'
services:
  rabbitmq:
    container_name: 'rabbitmq'
    image: 'bitnami/rabbitmq:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '4000:4369'
      - '5000:5672'
      - '15000:15672'
      - '25000:25672'
    volumes:
    - 'rabbitmq_data:/bitnami'
    networks:
      - local

volumes:
  rabbitmq_data:
    driver: local
networks:
  local:
    external: true